version: '3.8'

services:
  # Development container
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: cam-protocol/dev:latest
    container_name: cam-dev
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/node_modules
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - "8080:8080"
      - "9229:9229" # Node.js debug port
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - PORT=8080
      - OPENAI_API_KEY=sk-test-openai-key
      - ANTHROPIC_API_KEY=sk-ant-test-anthropic-key
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=cam_user
      - DB_PASSWORD=cam_password
      - DB_NAME=cam_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - postgres
    networks:
      - cam-network

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: cam-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - cam-network

  # PostgreSQL for persistent storage
  postgres:
    image: postgres:15-alpine
    container_name: cam-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=cam_user
      - POSTGRES_PASSWORD=cam_password
      - POSTGRES_DB=cam_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cam_user -d cam_db"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - cam-network

  # Demo OpenAI-compatible API service
  mock-openai:
    image: ghcr.io/complete-arbitration-mesh/mock-openai:latest
    container_name: cam-mock-openai-dev
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    networks:
      - cam-network

  # Demo Anthropic-compatible API service
  mock-anthropic:
    image: ghcr.io/complete-arbitration-mesh/mock-anthropic:latest
    container_name: cam-mock-anthropic-dev
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    networks:
      - cam-network

volumes:
  node_modules:
  redis-data:
  postgres-data:

networks:
  cam-network:
    driver: bridge
