apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: cam-system
data:
  redis.conf: |
    # Redis production configuration
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save 900 1
    save 300 10
    save 60 10000
    appendonly yes
    appendfsync everysec
    timeout 300
    tcp-keepalive 60
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cam-redis
  namespace: cam-system
  labels:
    app: cam-redis
spec:
  serviceName: cam-redis-service
  replicas: 1
  selector:
    matchLabels:
      app: cam-redis
  template:
    metadata:
      labels:
        app: cam-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - /etc/redis/redis.conf
        volumeMounts:
        - name: redis-config
          mountPath: /etc/redis
        - name: redis-data
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: cam-redis-service
  namespace: cam-system
  labels:
    app: cam-redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: cam-redis
  type: ClusterIP
