groups:
  - name: cam_protocol_alerts
    rules:
      # Performance Alerts
      - alert: HighLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{job="cam-core"}[5m])) by (le, route)) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "95th percentile latency for {{ $labels.route }} is above 2 seconds"

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{job="cam-core", status_code=~"5.."}[5m])) / sum(rate(http_requests_total{job="cam-core"}[5m])) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for the last 2 minutes"

      # Resource Utilization Alerts
      - alert: HighCPUUsage
        expr: process_cpu_seconds_total{job="cam-core"} > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for the last 5 minutes"

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes{job="cam-core"} / node_memory_MemTotal_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 80% for the last 5 minutes"

      # Service Health Alerts
      - alert: ServiceDown
        expr: up{job="cam-core"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "CAM Protocol service is down"
          description: "The CAM Protocol service has been down for more than 1 minute"

      - alert: HighRejectionRate
        expr: sum(rate(routing_decisions_total{job="cam-core", result="rejected"}[5m])) / sum(rate(routing_decisions_total{job="cam-core"}[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High routing rejection rate"
          description: "More than 10% of routing decisions are being rejected"

      # Cost Alerts
      - alert: HighCostRate
        expr: sum(rate(api_cost_total{job="cam-core"}[1h])) > 100
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "High API cost rate detected"
          description: "API costs are exceeding $100/hour"

      # Connection Alerts
      - alert: HighConnectionCount
        expr: sum(connections_current{job="cam-core"}) > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High number of connections"
          description: "More than 1000 concurrent connections for the last 5 minutes"
