{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cam-chart.fullname" . }}
  labels:
    {{- include "cam-chart.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "cam-chart.selectorLabels" . | nindent 6 }}
{{- end }}
---
{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cam-chart.fullname" . }}
  labels:
    {{- include "cam-chart.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "cam-chart.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- if .Values.networkPolicy.ingress.enabled }}
    - Ingress
    {{- end }}
    {{- if .Values.networkPolicy.egress.enabled }}
    - Egress
    {{- end }}
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    # Allow ingress from same namespace
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
        {{- if .Values.metrics.enabled }}
        - protocol: TCP
          port: {{ .Values.metrics.port }}
        {{- end }}
        {{- if .Values.grpc.enabled }}
        - protocol: TCP
          port: {{ .Values.grpc.port }}
        {{- end }}
    
    # Allow ingress from ingress controller
    {{- if .Values.ingress.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.ingress.ingressNamespace | default "ingress-nginx" }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
    {{- end }}
    
    # Allow ingress from monitoring namespace
    {{- if .Values.monitoring.enabled }}
    - from:
        - namespaceSelector:
            matchLabels:
              name: {{ .Values.networkPolicy.ingress.monitoringNamespace | default "monitoring" }}
      ports:
        - protocol: TCP
          port: {{ .Values.metrics.port }}
    {{- end }}
    
    # Custom ingress rules
    {{- with .Values.networkPolicy.ingress.rules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    
    # Allow HTTPS outbound
    - to: []
      ports:
        - protocol: TCP
          port: 443
    
    # Allow database access
    {{- if .Values.postgresql.enabled }}
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
      ports:
        - protocol: TCP
          port: {{ .Values.postgresql.primary.service.ports.postgresql }}
    {{- end }}
    
    # Allow Redis access
    {{- if .Values.redis.enabled }}
    - to:
        - namespaceSelector:
            matchLabels:
              name: {{ .Release.Namespace }}
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
      ports:
        - protocol: TCP
          port: {{ .Values.redis.master.service.ports.redis }}
    {{- end }}
    
    # Allow CAM mesh communication
    - to:
        - namespaceSelector: {}
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: cam-mesh
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
        {{- if .Values.grpc.enabled }}
        - protocol: TCP
          port: {{ .Values.grpc.port }}
        {{- end }}
    
    # Custom egress rules
    {{- with .Values.networkPolicy.egress.rules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
