{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cam-chart.serviceAccountName" . }}
  labels:
    {{- include "cam-chart.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cam-chart.fullname" . }}
  labels:
    {{- include "cam-chart.labels" . | nindent 4 }}
rules:
  # CAM Node Discovery and Communication
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  
  # ConfigMap and Secret access for dynamic configuration
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
    resourceNames:
      - {{ include "cam-chart.fullname" . }}-config
      - {{ include "cam-chart.fullname" . }}-secret
  
  # Node information for mesh topology
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  
  # Custom Resource Definitions for CAM protocols
  {{- if .Values.rbac.createCRDPermissions }}
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  
  - apiGroups: ["cam.protocol.io"]
    resources: ["*"]
    verbs: ["*"]
  {{- end }}
  
  # Events for logging and monitoring
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  
  # Additional permissions for mesh coordination
  {{- if .Values.rbac.meshCoordination.enabled }}
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  {{- end }}
  
  # Metrics and monitoring permissions
  {{- if .Values.monitoring.enabled }}
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cam-chart.fullname" . }}
  labels:
    {{- include "cam-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cam-chart.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cam-chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if .Values.rbac.createNamespaceRole }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "cam-chart.fullname" . }}-namespace
  labels:
    {{- include "cam-chart.labels" . | nindent 4 }}
rules:
  # Full access to resources in the same namespace
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  
  # Access to apps resources
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["*"]
  
  # Access to networking resources
  - apiGroups: ["networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  
  # Access to autoscaling resources
  - apiGroups: ["autoscaling"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "cam-chart.fullname" . }}-namespace
  labels:
    {{- include "cam-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cam-chart.fullname" . }}-namespace
subjects:
  - kind: ServiceAccount
    name: {{ include "cam-chart.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
