# CAM-OS Default Configuration
# Production-ready defaults for secure operation

# Server configuration
server:
  port: 50051
  metrics_port: 8080
  health_port: 8081
  host: "0.0.0.0"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

# Syscall timeout settings (H-2 requirement)
syscall:
  # Default timeout for all syscalls (500ms as specified in H-2)
  syscall_timeout: "500ms"
  # Specific timeouts for different operations
  arbitration_timeout: "100ms"
  memory_timeout: "50ms"
  security_timeout: "200ms"
  explainability_timeout: "75ms"

# Rate limiting (H-4 requirement foundation)
rate_limiting:
  max_requests_per_second: 1000
  burst_size: 100
  # Token bucket refill rate
  refill_interval: "1s"

# Security settings (H-4, H-5 requirements)
security:
  # mTLS configuration
  tls_enabled: true
  require_mtls: true
  cert_file: "/etc/cam-os/certs/server.crt"
  key_file: "/etc/cam-os/certs/server.key"
  ca_file: "/etc/cam-os/certs/ca.crt"
  
  # JWT configuration
  jwt_enabled: true
  jwt_signing_key_file: "/etc/cam-os/secrets/jwt.key"
  jwt_expiry: "1h"
  
  # OPA policy configuration
  opa_enabled: true
  opa_policy_path: "/etc/cam-os/policies"
  opa_endpoint: "http://localhost:8181"
  
  # Error redaction (H-5 requirement)
  redact_error_details: true
  
  # Audit logging
  enable_audit_logging: true
  audit_log_path: "/var/log/cam-os/audit.log"

# Validation settings (H-3 requirement foundation)
validation:
  max_namespace_length: 64
  max_key_length: 256
  max_payload_size: 1048576  # 1MB
  # Namespace sanitization patterns
  allowed_namespace_pattern: "^[a-z0-9_\\-]{1,64}$"
  allowed_key_pattern: "^[a-zA-Z0-9_\\-\\./]{1,256}$"
  allowed_agent_id_pattern: "^[a-zA-Z0-9_\\-]{1,128}$"

# TPM configuration (H-10 requirement)
tpm:
  enabled: true
  device_path: "/dev/tpm0"
  key_storage_path: "/var/lib/cam-os/tpm/keys"
  cert_chain_path: "/var/lib/cam-os/tpm/certs"
  
# Memory management
memory:
  max_contexts: 10000
  context_ttl: "24h"
  snapshot_retention: "7d"
  gc_interval: "1h"

# Observability
observability:
  tracing_enabled: true
  metrics_enabled: true
  trace_sampling_rate: 0.1  # 10% sampling in production
  metrics_path: "/metrics"
  health_path: "/health"

# Redis configuration
redis:
  url: "redis://localhost:6379"
  max_retries: 3
  retry_delay: "100ms"
  pool_size: 10
  pool_timeout: "5s"

# Logging
logging:
  level: "info"
  format: "json"
  output: "/var/log/cam-os/cam-os.log"
  max_size: "100MB"
  max_backups: 10
  max_age: "30d"
  compress: true

# Performance tuning
performance:
  max_workers: 100
  worker_queue_size: 1000
  connection_pool_size: 50
  keep_alive_time: "30s"
  keep_alive_timeout: "5s" 