apiVersion: v2
name: complete-arbitration-mesh
description: Complete Arbitration Mesh - Production-ready multi-agent arbitration system
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/cam-protocol/complete-arbitration-mesh
sources:
  - https://github.com/cam-protocol/complete-arbitration-mesh
maintainers:
  - name: CAM Team
    email: team@cam-protocol.org
keywords:
  - arbitration
  - mesh
  - multi-agent
  - microservices
  - ai
annotations:
  category: Application Framework
dependencies:
  - name: postgresql
    version: 12.1.9
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.4.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 15.18.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.50.7
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
