# Production Values for CAM-OS Kernel Helm Chart
# Pinned image tags for production stability

# Image configuration with pinned semver tags
image:
  repository: cam-os/kernel
  tag: "v2.1.0"  # PINNED: Update only after thorough testing
  pullPolicy: IfNotPresent
  
# Component-specific image tags
components:
  arbitration:
    image: cam-os/arbitration-engine
    tag: "v1.2.1"  # PINNED: Stable arbitration engine
    
  memory:
    image: cam-os/memory-manager  
    tag: "v1.1.3"  # PINNED: Memory context management
    
  security:
    image: cam-os/security-manager
    tag: "v2.0.2"  # PINNED: Post-quantum security
    
  explainability:
    image: cam-os/explainability-engine
    tag: "v1.0.4"  # PINNED: Audit and observability

# Infrastructure dependencies with pinned versions
dependencies:
  redis:
    image: redis
    tag: "7.2.4-alpine"  # PINNED: Stable Redis version
    
  prometheus:
    image: prom/prometheus
    tag: "v2.48.1"  # PINNED: Monitoring
    
  grafana:
    image: grafana/grafana
    tag: "10.2.3"  # PINNED: Dashboards

# Production resource limits
resources:
  kernel:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
      
  arbitration:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
      
  memory:
    requests:
      cpu: "300m"
      memory: "1Gi"
    limits:
      cpu: "1500m"
      memory: "8Gi"

# High availability configuration
replicaCount: 3

# Production autoscaling
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Production persistence
persistence:
  enabled: true
  storageClass: "fast-ssd"
  size: 100Gi
  
# Security configuration
security:
  podSecurityPolicy:
    enabled: true
  networkPolicy:
    enabled: true
  rbac:
    create: true
    
# Service configuration
service:
  type: ClusterIP
  port: 8080
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    
# Ingress with TLS
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: cam-os-prod.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: cam-os-prod-tls
      hosts:
        - cam-os-prod.example.com

# Production monitoring
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    
# Backup configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: 30  # Keep 30 days of backups
  
# Upgrade configuration
upgrade:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  
  # Pre-upgrade hooks
  preUpgrade:
    enabled: true
    backupDatabase: true
    validateConfig: true
    
  # Post-upgrade hooks  
  postUpgrade:
    enabled: true
    runSmokeTests: true
    validateHealth: true
    
# Environment-specific configuration
environment: production

# Feature flags for production
features:
  explainabilityEngine: true
  postQuantumSecurity: true
  advancedMetrics: true
  auditLogging: true
  
# Production-specific syscall limits
syscall:
  timeouts:
    arbitration: 100ms
    memory: 50ms
    security: 200ms
    explainability: 75ms
  
  rateLimits:
    requestsPerSecond: 1000
    burstSize: 100
    
  validation:
    strictMode: true
    sanitizeErrors: true

# Redis configuration for production
redis:
  auth:
    enabled: true
    password: "${REDIS_PASSWORD}"  # Set via secret
  persistence:
    enabled: true
    size: 50Gi
  replica:
    replicaCount: 2
    
# Prometheus configuration
prometheus:
  retention: "30d"
  storage:
    size: 100Gi
    
# Production alerts
alerts:
  enabled: true
  rules:
    - name: cam-os-high-latency
      condition: "avg(cam_syscall_duration_seconds) > 0.001"  # >1ms
      severity: warning
      
    - name: cam-os-high-error-rate
      condition: "rate(cam_syscall_errors_total[5m]) > 0.01"  # >1% error rate
      severity: critical
      
    - name: cam-os-memory-usage
      condition: "container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.9"
      severity: warning

# Production secrets (reference external secrets)
secrets:
  tpmKeys: "cam-os-tpm-keys"
  redisPassword: "cam-os-redis-password"
  jwtSigningKey: "cam-os-jwt-signing-key"
  
# Node affinity for production workloads
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: node-type
        operator: In
        values: ["compute-optimized"]
        
# Pod disruption budget
podDisruptionBudget:
  enabled: true
